name: EditorPerRepo

on:
  release:
    types: [created]

jobs:
  publish-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MY_TOKEN: ${{secrets.GITHUB_TOKEN}}



#name: EditorPerRepo
#
#on:
#  release:
#    types: [created]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        width:
#          node-version: 20
#      - run: npm ci
#      - run: npm test
#
#  publish-to-github:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      env:
#        MY_TOKEN: ${{secrets.GITHUB_TOKEN}}
